apiVersion: apps/v1
kind: Deployment
metadata:
  name: bk-deployment
  labels:
    app: bk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bk

  template:
    metadata:
      labels:
        app: bk
    spec:

      terminationGracePeriodSeconds: 20
      volumes:
        - name: bk-configmap-volume
          configMap:
            name: bk-configmap

      containers:

        - name: bk
          image: gcr.io/bootiful/bk
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          volumeMounts:
            - name: bk-configmap-volume
              mountPath: "/config"
              readOnly: true
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "cloud"
            - name: SERVER_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              hostPort: 80


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bk-configmap
data:
  execution-environment: "Kubernetes"
  server.port: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: bk-service
spec:
  type: LoadBalancer
  selector:
    app: bk
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP